"""init

Revision ID: 351636414ed5
Revises: 
Create Date: 2026-06-23 16:19:27.604589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351636414ed5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_base_url', sa.String(), nullable=True),
    sa.Column('ai_api_key', sa.String(), nullable=True),
    sa.Column('embed_model', sa.String(), nullable=True),
    sa.Column('embed_dim', sa.Integer(), nullable=True),
    sa.Column('chat_model', sa.String(), nullable=True),
    sa.Column('link_threshold_auto', sa.Float(), nullable=False),
    sa.Column('link_threshold_suggest', sa.Float(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thought_atom',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_device', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_embedding',
    sa.Column('atom_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['thought_atom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('atom_id')
    )
    op.create_table('thought_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_atom_id', sa.String(), nullable=False),
    sa.Column('to_atom_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_ignored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_atom_id'], ['thought_atom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_atom_id'], ['thought_atom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_atom_id', 'to_atom_id', 'link_type', name='uq_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thought_link')
    op.drop_table('atom_embedding')
    op.drop_table('thought_atom')
    op.drop_table('task_queue')
    op.drop_table('settings')
    # ### end Alembic commands ###
