"""split ai_provider into embed and chat configs

Revision ID: b72132d3c5c2
Revises: c4d2e8f1a9b0
Create Date: 2026-06-29 23:31:44.369687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72132d3c5c2'
down_revision: Union[str, Sequence[str], None] = 'c4d2e8f1a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('embed_base_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('embed_api_key', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('chat_base_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('chat_api_key', sa.String(), nullable=True))
    # 将旧字段数据复制到新字段
    op.execute("UPDATE settings SET embed_base_url = ai_base_url, embed_api_key = ai_api_key")
    op.drop_column('settings', 'ai_api_key')
    op.drop_column('settings', 'ai_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('ai_base_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('ai_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # 恢复数据
    op.execute("UPDATE settings SET ai_base_url = embed_base_url, ai_api_key = embed_api_key")
    op.drop_column('settings', 'chat_api_key')
    op.drop_column('settings', 'chat_base_url')
    op.drop_column('settings', 'embed_api_key')
    op.drop_column('settings', 'embed_base_url')
    # ### end Alembic commands ###
